name: Render Blueprint Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'render.yaml'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Blueprint Deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_BLUEPRINT_ID: ${{ secrets.RENDER_BLUEPRINT_ID }}
          BRANCH: ${{ github.event.inputs.branch || 'main' }}
        run: |
          if [ -z "$RENDER_API_KEY" ]; then
            echo "Missing RENDER_API_KEY secret" >&2
            exit 1
          fi
          if [ -z "$RENDER_BLUEPRINT_ID" ]; then
            echo "Missing RENDER_BLUEPRINT_ID secret" >&2
            exit 1
          fi
          curl -fsSL -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"branch\": \"$BRANCH\"}" \
            "https://api.render.com/v1/blueprints/$RENDER_BLUEPRINT_ID/deploys"
